name: Build static library dependencies
on:
  workflow_dispatch:

  push:
    branches-ignore:
      - master
    paths:
      - ".github/workflows/**"
      - "duckdb.cpp"
      - "duckdb.h"
      - "duckdb.hpp"
jobs:
  windows_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Build Wails app
        run: |
          x86_64-w64-mingw32-g++ --version
          x86_64-w64-mingw32-g++ -Og -std=c++11 -DGODUCKDB_FROM_SOURCE -static-libstdc++ -static-libgcc -m64 "-Wa,-mbig-obj" -c duckdb.cpp -o duckdb.o
	        x86_64-w64-mingw32-ar crs libduckdb.a duckdb.o
          ls -alh
      - uses: actions/upload-artifact@v3
        with:
          name: windows_amd64
          path: deps/windows_amd64/libduckdb.a
          retention-days: 1
